version: '3.1'

services:

  back:
    container_name: "back"
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on: # Wait for 'mysql' container to start before starting 'back'
      - mysql
    env_file:
      - ./back/.env
    networks: 
      - stack-net
    
  front:
    # image: front
    container_name: "front"
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./front/.env
    networks: 
      - stack-net

  mysql:
    image: mysql
    container_name: "mysql"
    # command: mysqld --user=root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      # - MYSQL_HOST=localhost
      - MYSQL_DATABASE=auth
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./dump:/docker-entrypoint-initdb.d
    networks: 
      - stack-net
networks:
  stack-net:
    external: true